# DB migration config for Hbacker tool

migration:
  adapter: mysql
  host: Shantanu-Kumars-MacBook-Pro.local
  database: hbacker
  pool: 5
  timeout: 5000
  username: root
  password: password

crud:
  adapter: mysql
  host: Shantanu-Kumars-MacBook-Pro.local
  database: hbacker
  pool: 5
  timeout: 5000
  username: root
  password: password
